### ISSUE TITLE
"Only running on first push of a new branch" error even on first push

### ISSUE THREAD

**Issue by dschep** [greenkeeperio/greenkeeper-lockfile#26]
I was hoping to make use of this to update my `yarn.lock` but the first branch pushed from @greenkeeperio  printed out this message:
```
Only running on first push of a new branch
```

This is on a private CircleCI repo.

**Comment by finnp** [comment]
Hey @dschep,

is this the `greenkeeper/initial` branch? Since the initial requests has multiple commits, it might be wrongfully detected as a second push.

**Comment by dschep** [comment]
Nope, it was a package upgrade branch (and only had 1 commit)

**Comment by finnp** [comment]
Do you see any reason why the detection of the numbers of commits in [git-helpers.js](https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/lib/git-helpers.js) could have failed for your setup? 

I just tested this locally and it was fine. Might be helpful to ssh into the job on CircleCI to see what the result of that command is.

**Comment by dschep** [comment]
Nope, I tested the same branch and on the same docker image as our CI uses and couldn't reproduce it. Had other stuff to work on so I pretty much just homebrewed my own solution using the same tactic, but less logic:
```
- run: echo $CIRCLE_BRANCH | egrep '^greenkeeper/' && yarn || yarn --frozen-lockfile
# later..
- run: echo $CIRCLE_BRANCH | egrep '^greenkeeper/' && git add yarn.lock && git commit -m 'yarn' || true && git push origin $CIRCLE_BRANCH
```

**Comment by ethanrubio** [comment]
This should be fixed now with this https://github.com/greenkeeperio/greenkeeper-lockfile/pull/32 PR. Please reopen if there are other issues.

**Comment by patkub** [comment]
Still getting this issue on CircleCI.
Branch: https://github.com/patkub/rmc1891-site/tree/greenkeeper/bs4-polymer-0.1.12
CircleCI: https://circleci.com/gh/patkub/rmc1891-site/736
